name: Update LeetCode Stats

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:
  # Run on push to main branch (for testing)
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run LeetCode Stats Updater
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      run: |
        python leetcode_stats_updater.py
        if [ $? -ne 0 ]; then
          echo "Script failed with exit code $?"
          exit 1
        fi
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add dsa/leetcode_stats.md
        git commit -m "Update LeetCode stats [skip ci]"
        git push 